# Generated by Faunus — run with: vmd -e traj.tcl
mol load psf traj.psf xtc traj.xtc
mol modstyle 0 top VDW 1.0 12.0
mol modcolor 0 top Charge
pbc box
set sel [atomselect top {type SP}]; $sel set radius 20.0000; $sel delete

# --- Per-frame charge update for titration ---
set charge_data {}
set _fp [open "traj.charges.dat" r]
while {[gets $_fp _line] >= 0} {
    set _line [string trim $_line]
    if {$_line ne ""} {
        lappend charge_data [list {*}$_line]
    }
}
close $_fp

proc faunus_update_charges {args} {
    global vmd_frame charge_data
    set f $vmd_frame(0)
    if {$f >= [llength $charge_data]} return
    set charges [lindex $charge_data $f]
    set _all [atomselect top "all"]
    $_all set charge $charges
    $_all delete
}

if {[llength $charge_data] > 0} {
    trace variable vmd_frame(0) w faunus_update_charges
    faunus_update_charges
}
